server:
  port: 9090
  servlet:
    context-path: /e-journal
# spring
spring:
  application:
    name: '@project.artifactId@'
cors:
  pathMapping: '/**'
  allowedOrigins: 'http://localhost:3000'
  allowedMethods: 'GET,POST,PUT,DELETE'

